<a href="https://colab.research.google.com/github/Saharuth/python_project/blob/AI/model_mean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Fri Jun 30 13:21:16 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   71C    P8    13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import tensorflow as tf
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
import numpy as np

Ex โจทย์ สร้าง model ในการหา "ค่าเฉลี่ย" จากชุดตัวเลขเป็นจำนวนเต็มบวกชุดละ 6 ตัว

In [3]:
result = np.random.randint(100, size=(1000,6))/100
print(result)

[[0.83 0.17 0.64 0.49 0.82 0.73]
 [0.78 0.15 0.37 0.97 0.61 0.56]
 [0.14 0.26 0.59 0.69 0.27 0.19]
 ...
 [0.1  0.61 0.57 0.28 0.11 0.7 ]
 [0.97 0.25 0.61 0.65 0.04 0.1 ]
 [0.83 0.56 0.49 0.59 0.27 0.91]]


In [4]:
train = np.random.randint(100, size=(10000,6))/100
val = np.random.randint(100, size=(1000,6))/100
test = np.random.randint(100, size=(1000,6))/100

เริ่มจากการสอนแบบ Supervise Learning ----> ดำเนินการทำเฉลยให้กับ dataset ทั้งหมด

In [5]:
train_ans = train.mean(axis=1)
val_ans = val.mean(axis=1)
test_ans = test.mean(axis=1)

In [6]:
model = Sequential()
model.add(Dense(8, input_shape=(6,)))
model.add(Dense(8))
model.add(Dense(1))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 56        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 137
Trainable params: 137
Non-trainable params: 0
_________________________________________________________________


Sequential คือ ต่อกันเป็น layer อย่างชัดเจน
ส่วนแบบ Funtional คือ ต่อกันแยกเป็นหลายขาได้ หยืดหยุ่นกว่า ซับซ้อนได้มากกว่า

In [7]:
model.compile(loss="mse", optimizer=tf.keras.optimizers.SGD())
model.fit(
    x = train,
    y = train_ans,
    epochs = 10,
    batch_size = 100,
    validation_data = (val, val_ans),
    validation_batch_size = 100
)

Epoch 1/10
100/100 [==============================] - 2s 4ms/step - loss: 0.0162 - val_loss: 0.0106
Epoch 2/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0087 - val_loss: 0.0071
Epoch 3/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0062 - val_loss: 0.0053
Epoch 4/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0047 - val_loss: 0.0041
Epoch 5/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0038 - val_loss: 0.0033
Epoch 6/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0031 - val_loss: 0.0028
Epoch 7/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0025 - val_loss: 0.0023
Epoch 8/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0021 - val_loss: 0.0019
Epoch 9/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0018 - val_loss: 0.0016
Epoch 10/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0015 - val_loss: 0.0014

In [10]:
predic = model.predict(test)
print(predic[:5])
print(test_ans[:5])

32/32 [==============================] - 0s 1ms/step
[[0.5534303 ]
 [0.37634444]
 [0.2579824 ]
 [0.57172424]
 [0.22678228]]
[0.57166667 0.40333333 0.22833333 0.595      0.23166667]
