In [2]:
!nvidia-smi

Sat Jul  1 14:14:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import tensorflow as tf
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
import numpy as np

Ex ให้สร้าง model ทำนายเลขในลำดับถัดไป โดยทำนายจากชุดตัวเลข 5 ตัว (ชุดตัวเลขเป็นเลขลำดับการคูณ)
[1 2 4 8 16] => 32

In [4]:
def create_dataset(number):
  total = []
  total_y = []
  for y in range(number):
    rand = (np.random.randint(5)+1)
    multiply = (np.random.randint(5)+1)
    res = [ rand*(multiply**x)/10000 for x in range(5)]
    total.append(res)
    total_y.append(rand*(multiply**5)/10000)
  return np.array(total), np.array(total_y)

train, train_ans = create_dataset(10000)
val, val_ans = create_dataset(1000)
test, test_ans = create_dataset(1000)
print(train, train_ans)

[[0.0001 0.0005 0.0025 0.0125 0.0625]
 [0.0001 0.0004 0.0016 0.0064 0.0256]
 [0.0001 0.0004 0.0016 0.0064 0.0256]
 ...
 [0.0001 0.0003 0.0009 0.0027 0.0081]
 [0.0005 0.001  0.002  0.004  0.008 ]
 [0.0004 0.0012 0.0036 0.0108 0.0324]] [0.3125 0.1024 0.1024 ... 0.0243 0.016  0.0972]


In [5]:
model = Sequential()
model.add(Dense(8, input_shape=(5,)))
model.add(Dense(8))
model.add(Dense(1))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 48        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 129
Trainable params: 129
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.compile(loss="mse", optimizer=tf.keras.optimizers.SGD())
model.fit(
    x = train,
    y = train_ans,
    epochs = 100,
    batch_size = 100,
    validation_data = (val, val_ans),
    validation_batch_size = 100
)

Epoch 1/100
100/100 [==============================] - 2s 4ms/step - loss: 0.1647 - val_loss: 0.1360
Epoch 2/100
100/100 [==============================] - 0s 3ms/step - loss: 0.1409 - val_loss: 0.1233
Epoch 3/100
100/100 [==============================] - 0s 3ms/step - loss: 0.1266 - val_loss: 0.1096
Epoch 4/100
100/100 [==============================] - 0s 4ms/step - loss: 0.1110 - val_loss: 0.0947
Epoch 5/100
100/100 [==============================] - 0s 3ms/step - loss: 0.0943 - val_loss: 0.0790
Epoch 6/100
100/100 [==============================] - 0s 3ms/step - loss: 0.0770 - val_loss: 0.0629
Epoch 7/100
100/100 [==============================] - 0s 3ms/step - loss: 0.0597 - val_loss: 0.0475
Epoch 8/100
100/100 [==============================] - 0s 3ms/step - loss: 0.0438 - val_loss: 0.0337
Epoch 9/100
100/100 [==============================] - 0s 3ms/step - loss: 0.0302 - val_loss: 0.0226
Epoch 10/100
100/100 [==============================] - 0s 3ms/step - loss: 0.0196 - val_lo

In [7]:
predic = model.predict(test)
print(predic[:5])
print(test_ans[:5])

32/32 [==============================] - 0s 2ms/step
[[-0.03084814]
 [ 0.1322324 ]
 [ 0.1322324 ]
 [ 0.05038825]
 [ 1.216882  ]]
[1.00e-04 9.72e-02 9.72e-02 4.86e-02 1.25e+00]
